#!/bin/sh
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ]; then
  echo "❌ ERROR: Estás en la rama 'main'."
  echo "Para evitar problemas, está prohibido guardar cambios directamente aquí."
  echo "👉 Crea una rama nueva para tu tarea (ej: git checkout -b feature/mi-tarea)"
  exit 1
fi
