import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

type Language = 'es' | 'en' | 'zh';

interface Translations {
    [key: string]: {
        es: string;
        en: string;
        zh?: string;
    };
}

export const translations: Translations = {
    // Truck Tracking
    "truck.title": { es: "TRUCK_TRACKING", en: "TRUCK_TRACKING", zh: "卡车跟踪" },
    "truck.subtitle": { es: "Seguimiento de unidades y estado de liberación operativa", en: "Unit tracking and operational release status", zh: "单位跟踪和操作放行状态" },
    "truck.inicio": { es: "Inicio", en: "Start", zh: "开始" },
    "truck.fin": { es: "Fin", en: "End", zh: "结束" },
    "truck.recargar": { es: "Recargar", en: "Reload", zh: "重新加载" },
    "truck.descargar_csv": { es: "Descargar CSV", en: "Download CSV", zh: "下载 CSV" },
    "truck.total_asignadas": { es: "Total Asignadas", en: "Total Assigned", zh: "总分配" },
    "truck.liberadas": { es: "Liberadas", en: "Released", zh: "已放行" },
    "truck.pendientes": { es: "Pendientes", en: "Pending", zh: "待处理" },
    "truck.pendientes_text": { es: "pendientes", en: "pending", zh: "待处理" },
    "truck.completado": { es: "% completado", en: "% completed", zh: "完成百分比" },
    "truck.progreso_lib": { es: "Progreso de Liberación", en: "Release Progress", zh: "放行进度" },
    "truck.cajas": { es: "cajas", en: "vans", zh: "货车" },
    "truck.buscar": { es: "Buscar por caja, chofer, placas, operación...", en: "Search by van, driver, plates, operation...", zh: "按货车、司机、车牌、操作搜索..." },
    "truck.estado_docks": { es: "Estado de Docks", en: "Dock Status", zh: "月台状态" },
    "truck.ocupados": { es: "Ocupados", en: "Occupied", zh: "占用" },
    "truck.libres": { es: "Libres", en: "Free", zh: "空闲" },
    "truck.libre": { es: "libre", en: "free", zh: "空闲" },
    "truck.vehiculos": { es: "vehículos", en: "vehicles", zh: "车辆" },
    "filter.en_proceso": { es: "EN PROCESO", en: "IN PROCESS", zh: "进行中" },
    "filter.pendientes": { es: "PENDIENTES", en: "PENDING", zh: "待处理" },
    "truck.en_patio": { es: "(en patio)", en: "(in yard)", zh: "(在堆场)" },
    "truck.temprano": { es: "Temprano", en: "Early", zh: "早到" },
    "truck.col.hora": { es: "HORA", en: "TIME", zh: "时间" },
    "truck.col.arribo": { es: "ARRIBO", en: "DOCK ASSIGNATION", zh: "到达" },
    "truck.col.operacion": { es: "OPERACIÓN", en: "OPERATION", zh: "操作" },
    "truck.col.caja": { es: "CAJA (53-FT)", en: "DRY VAN (53-FT)", zh: "干货车 (53-FT)" },
    "truck.col.driver": { es: "DRIVER", en: "DRIVER", zh: "司机" },
    "truck.col.placas_tracto": { es: "PLACAS TRACTO", en: "TRUCK PLATES", zh: "牵引车牌" },
    "truck.col.placas_caja": { es: "PLACAS CAJA", en: "VAN PLATES", zh: "货车车牌" },
    "truck.col.scac": { es: "SCAC", en: "SCAC", zh: "SCAC" },
    "truck.col.sublinea": { es: "SUB-LÍNEA", en: "SUB-LINE", zh: "子线路" },
    "truck.col.modelo": { es: "MODELO", en: "MODEL", zh: "型号" },
    "truck.col.creado_por": { es: "CREADO POR", en: "CREATED BY", zh: "创建人" },
    "truck.col.creado_at": { es: "CREADO AT", en: "BOOKING CREATION", zh: "创建时间" },
    "truck.col.layout_por": { es: "LAYOUT SUBIDO POR", en: "LAYOUT UPLOADED BY", zh: "布局上传人" },
    "truck.col.layout_at": { es: "LAYOUT AT", en: "LAYOUT UPLOAD", zh: "布局时间" },
    "truck.col.ccp_por": { es: "CCP SUBIDO POR", en: "CCP UPLOADED BY", zh: "CCP上传人" },
    "truck.col.ccp_at": { es: "CCP AT", en: "CCP UPLOAD", zh: "CCP时间" },
    "truck.col.lib_dock": { es: "LIBERACIÓN DOCK", en: "DOCK RELEASE", zh: "月台放行" },
    "truck.col.lib_por": { es: "LIBERADO POR", en: "SHIPMENT RELEASE", zh: "放行人" },
    "truck.col.status": { es: "STATUS", en: "STATUS", zh: "状态" },
    "truck.col.retraso": { es: "TIEMPO DE RETRASO", en: "ARRIVAL DELAY", zh: "延迟时间" },
    "truck.col.en_planta": { es: "TIEMPO EN PLANTA", en: "TIME IN PLANT", zh: "厂内时间" },
    "truck.col.ly_ccp": { es: "LY&CCP", en: "LY&CCP", zh: "LY&CCP" },
    "truck.col.t_cierre": { es: "T.CIERRE", en: "CLOSE TIME", zh: "关闭时间" },
    "truck.col.fecha": { es: "FECHA", en: "DATE", zh: "日期" },
    "truck.col.dock_arribo": { es: "DOCK ASIGNADO", en: "ASSIGNED DOCK", zh: "指定月台" },
    "truck.col.comentarios_arribo": { es: "COMENTARIOS ARRIBO", en: "ARRIVAL COMMENTS", zh: "到达备注" },
    "truck.col.dealer": { es: "DEALER ASIGNADO", en: "ASSIGNED DEALER", zh: "指定经销商" },
    "truck.col.observaciones": { es: "OBSERVACIONES", en: "OBSERVATIONS", zh: "观察" },
    "truck.col.carrier_ref": { es: "CARRIER REF", en: "CARRIER REF", zh: "承运商参考" },
    "truck.col.notas": { es: "NOTAS", en: "NOTES", zh: "笔记" },
    "truck.col.anexo29_por": { es: "ANEXO 29 POR", en: "ANEXO 29 UPLOADED BY", zh: "附件29上传人" },
    "truck.col.anexo29_at": { es: "ANEXO 29 AT", en: "ANEXO 29 AT", zh: "附件29时间" },
    "truck.liberado": { es: "LIBERADO", en: "RELEASED", zh: "已放行" },
    "truck.pendiente": { es: "PENDIENTE", en: "PENDING", zh: "待处理" },
    // Menú Principal y Títulos Operativos
    "menu.cajas": { es: "Catálogo de Cajas Secas 53'", en: "53-foot Dry Van Catalog" },
    "menu.asignaciones": { es: "Asignación Diaria de Cajas", en: "Daily 53' Dry Van Assignment" },
    "menu.drivers": { es: "Directorio de Choferes", en: "Drivers Directory" },
    "menu.líneas": { es: "Líneas de Tracto Camión", en: "Truck Tractor Lines" },
    "menu.carriers": { es: "Catálogo de Transportistas", en: "Carriers Catalog" },
    "menu.dashboard": { es: "Dashboard", en: "Dashboard" },
    "menu.plan": { es: "Shipment Plan", en: "Shipment Plan" },
    "menu.prealerts": { es: "Pre-Alerts", en: "Pre-Alerts" },
    "menu.tracking": { es: "Tracking", en: "Tracking" },
    "menu.equipment": { es: "Equipment", en: "Equipment" },
    "menu.customs": { es: "Customs Clearance", en: "Customs Clearance" },
    "menu.ciextractor": { es: "CI Extractor", en: "CI Extractor" },
    "menu.ai": { es: "Asistente IA", en: "AI Assistant" },
    
    // Módulo de Asignaciones Diarias Específico
    "asig.title": { es: "Asignación Diaria de Cajas Secas 53'", en: "Daily 53-foot Dry Van Assignment", zh: "53英尺干货车日常分配" },
    "asig.subtitle": { es: "Gestión operativa vinculando Cajas Secas 53' y Transportistas activos.", en: "Operational management linking 53' Dry Vans and active Carriers.", zh: "连接53英尺干货车与活跃承运人的运营管理。" },
    "asig.buscar": { es: "Búsqueda multi-termino (Operación, Caja, Driver, Placas, Transportista, Sellos, etc)...", en: "Multi-term search (Operation, Box, Driver, Plates, Carrier, Seals, etc)...", zh: "多条件搜索（操作、箱号、司机、车牌、承运人、封条等）..." },

    // Advanced Query Builder
    "qb.title": { es: "Constructor de Consultas Avanzadas", en: "Advanced Query Builder", zh: "高级查询构建器" },
    "qb.subtitle": { es: "Combina múltiples filtros para encontrar registros específicos.", en: "Combine multiple filters to find specific records in this catalog.", zh: "组合多个筛选条件查找特定记录。" },
    "qb.column": { es: "Columna", en: "Column", zh: "列" },
    "qb.operator": { es: "Operador", en: "Operator", zh: "运算符" },
    "qb.datatype": { es: "Tipo de Dato", en: "Data Type", zh: "数据类型" },
    "qb.op_in": { es: "(in) en lista", en: "(in) in list", zh: "(in) 在列表中" },
    "qb.op_eq": { es: "(==) igual a", en: "(==) equal to", zh: "(==) 等于" },
    "qb.op_neq": { es: "(!=) distinto de", en: "(!=) not equal to", zh: "(!=) 不等于" },
    "qb.op_contains": { es: "contiene", en: "contains", zh: "包含" },
    "qb.op_notcontains": { es: "no contiene", en: "not contains", zh: "不包含" },
    "qb.op_empty": { es: "está vacío / null", en: "is empty / null", zh: "为空 / null" },
    "qb.op_notempty": { es: "NO está vacío", en: "is NOT empty", zh: "不为空" },
    "qb.type_string": { es: "Texto (String)", en: "String (Text)", zh: "文本 (String)" },
    "qb.type_number": { es: "Número", en: "Number", zh: "数字" },
    "qb.type_boolean": { es: "Booleano", en: "Boolean", zh: "布尔值" },
    "qb.val_noreq": { es: "Valor (No requerido para este operador)", en: "Value (Not required for this operator)", zh: "值（此运算符不需要）" },
    "qb.val_list": { es: "Valores (uno por línea o separados por coma)", en: "Values (One per line or comma-separated)", zh: "值（每行一个或逗号分隔）" },
    "qb.val_target": { es: "Valor objetivo", en: "Target Value", zh: "目标值" },
    "qb.placeholder_in": { es: "Ejemplo:\nVal1 Val2 Val3\n(Separar por espacio, coma o nueva línea)", en: "Example:\nVal1 Val2 Val3\n(Separate by space, comma or newline)", zh: "示例：\nVal1 Val2 Val3\n（用空格、逗号或换行分隔）" },
    "qb.placeholder_val": { es: "Ingresa el valor objetivo...", en: "Enter target value...", zh: "输入目标值..." },
    "qb.add_condition": { es: "+ Agregar Condición", en: "+ Add Another Condition", zh: "+ 添加条件" },
    "qb.reset": { es: "Restablecer Todo", en: "Reset All", zh: "重置全部" },
    "qb.cancel": { es: "Cancelar", en: "Cancel", zh: "取消" },
    "qb.apply": { es: "Aplicar Filtro Complejo", en: "Apply Complex Filter", zh: "应用复杂筛选" },

    // Embarques y Check-in
    "emb.title": { es: "Embarques", en: "Shipments", zh: "发货" },
    "emb.subtitle": { es: "Gestión de unidades en sitio y asignación de Docks", en: "On-site unit management and Dock assignment", zh: "现场车辆管理及月台分配" },
    "emb.tab.todos": { es: "TODOS", en: "ALL", zh: "全部" },
    "emb.tab.con_layout": { es: "CON LAYOUT", en: "WITH LAYOUT", zh: "带布局" },
    "emb.tab.con_ccp": { es: "CON CCP", en: "WITH CCP", zh: "带CCP" },
    "emb.tab.sin_cierre": { es: "SIN CIERREEMB", en: "NO CLOSE", zh: "未关闭" },
    "emb.tab.check_in": { es: "CHECK-IN", en: "CHECK-IN", zh: "签到" },
    "emb.filter.todos": { es: "Todos los estatus", en: "All statuses", zh: "所有状态" },
    "emb.filter.con_cita": { es: "Con Cita", en: "With Appt", zh: "有预约" },
    "emb.filter.sin_cita": { es: "Sin Cita", en: "No Appt", zh: "无预约" },
    "emb.filter.con_errores": { es: "Con Errores", en: "With Errors", zh: "有错误" },
    "emb.col.arribo": { es: "ARRIBO", en: "ARRIVAL", zh: "到达" },
    "emb.col.operacion": { es: "NO. OPERACIÓN", en: "OPERATION NO.", zh: "操作编号" },
    "emb.col.caja": { es: "CAJA / PLACAS", en: "TRAILER / PLATES", zh: "货车 / 车牌" },
    "emb.col.linea": { es: "LÍNEA", en: "LINE", zh: "线路" },
    "emb.col.scac": { es: "SCAC", en: "SCAC", zh: "SCAC" },
    "emb.col.carrier_ref": { es: "CARRIER REF", en: "CARRIER REF", zh: "承运人参考" },
    "emb.col.celular": { es: "CELULAR", en: "PHONE", zh: "手机" },
    "emb.col.estatus": { es: "ESTATUS", en: "STATUS", zh: "状态" },
    "emb.col.asignar_dock": { es: "ASIGNAR DOCK", en: "ASSIGN DOCK", zh: "分配月台" },
    "emb.btn.guardar": { es: "Guardar", en: "Save", zh: "保存" },
    "emb.dock.select": { es: "Seleccionar Dock", en: "Select Dock", zh: "选择月台" },
    "emb.empty": { es: "No hay check-ins registrados en estas fechas.", en: "No check-ins registered on these dates.", zh: "这些日期没有签到记录。" },
    "emb.stats.todos": { es: "Todos", en: "All", zh: "全部" },
    "emb.stats.con_layout": { es: "Con Layout", en: "With Layout", zh: "带布局" },
    "emb.stats.con_ccp": { es: "Con CCP", en: "With CCP", zh: "带CCP" },
    "emb.stats.sin_cierre": { es: "Sin CierreEmb", en: "No Close", zh: "未关闭" },

    // Histórico Expo
    "he.title": { es: "Histórico Expo", en: "Export History", zh: "出口历史" },
    "he.subtitle": { es: "Registro de Control de Operaciones", en: "Operations Control Log", zh: "操作控制日志" },
    "he.tab.todos": { es: "Todos", en: "All", zh: "全部" },
    "he.tab.por_cerrar": { es: "POR CERRAR", en: "TO CLOSE", zh: "待关闭" },
    "he.tab.cerrado": { es: "CERRADO", en: "CLOSED", zh: "已关闭" },
    "he.search": { es: "Buscar caja, CFM Ref...", en: "Search trailer, CFM Ref...", zh: "搜索货车, CFM Ref..." },
    "he.hoy": { es: "HOY", en: "TODAY", zh: "今天" },
    "he.filtros": { es: "Filtros Masivos", en: "Mass Filters", zh: "批量过滤" },
    "he.col.trailer": { es: "TRAILER", en: "TRAILER", zh: "货车" },
    "he.col.idnumber": { es: "IDNUMBER", en: "IDNUMBER", zh: "IDNUMBER" },
    "he.col.seal": { es: "SEAL", en: "SEAL", zh: "封条" },
    "he.col.vehiculos": { es: "VEHICULOS", en: "VEHICLES", zh: "车辆" },
    "he.col.team": { es: "TEAM", en: "TEAM", zh: "团队" },
    "he.col.linea": { es: "LÍNEA TRANSPORTE", en: "TRANSPORT LINE", zh: "运输线路" },
    "he.col.cfmref": { es: "CFM REF", en: "CFM REF", zh: "CFM REF" },
    "he.col.pickup": { es: "PICKUP DAY CFM", en: "PICKUP DAY CFM", zh: "CFM提货日期" },
    "he.col.scac": { es: "SCAC", en: "SCAC", zh: "SCAC" },
    "he.col.caat": { es: "CAAT", en: "CAAT", zh: "CAAT" },
    "he.col.doda": { es: "DODA", en: "DODA", zh: "DODA" },
    "he.col.entry": { es: "ENTRY", en: "ENTRY", zh: "ENTRY" },
    "he.col.doda_date": { es: "DODA APERTURE DATE", en: "DODA APERTURE DATE", zh: "DODA开启日期" },
    "he.col.entry_date": { es: "ENTRY APERTURE DATE", en: "ENTRY APERTURE DATE", zh: "ENTRY开启日期" },
    "he.col.req_date": { es: "DATE REQUESTED", en: "DATE REQUESTED", zh: "请求日期" },
    "he.col.cross_date": { es: "CROSSING DATE", en: "CROSSING DATE", zh: "过境日期" },
    "he.col.rec_date": { es: "Date Received", en: "Date Received", zh: "收到日期" },
    "he.col.days_rec": { es: "Days to Receive", en: "Days to Receive", zh: "接收天数" },
    "he.col.exp_doda": { es: "EXP DODA", en: "EXP DODA", zh: "EXP DODA" },
    "he.col.comments": { es: "COMMENTS", en: "COMMENTS", zh: "评论" },
    "he.col.deliv_date": { es: "DELIVERY DATE", en: "DELIVERY DATE", zh: "交货日期" },
    "he.col.ata_dest": { es: "ATA DESTINATION", en: "ATA DESTINATION", zh: "ATA目的地" },
    "btn.new": { es: "Asignar", en: "Assign", zh: "分配" },
    "btn.export": { es: "Exportar", en: "Export", zh: "导出" },
    "btn.mass": { es: "Filtros Masivos", en: "Mass Filters", zh: "批量筛选" },
    "btn.actualizar": { es: "Actualizar", en: "Update", zh: "更新" },
    "btn.actualizando": { es: "Actualizando...", en: "Updating...", zh: "更新中..." },
    "btn.borrar": { es: "Borrar", en: "Delete", zh: "删除" },
    "btn.cierre": { es: "Cierre", en: "Close", zh: "关闭" },
    "btn.cerrando": { es: "Cerrando...", en: "Closing...", zh: "关闭中..." },
    "btn.cierre_title": { es: "Cierre manual de operaciones pendientes con CCP", en: "Manual closure of pending operations with CCP", zh: "手动关闭待处理CCP操作" },
    "common.hoy": { es: "HOY", en: "TODAY", zh: "今天" },
    "common.buscar": { es: "Búsqueda multi-termino...", en: "Multi-term search...", zh: "多条件搜索..." },
    "common.fecha_inicial": { es: "Fecha Inicial", en: "Start Date", zh: "开始日期" },
    "common.fecha_final": { es: "Fecha Final", en: "End Date", zh: "结束日期" },
    "col.fecha": { es: "Fecha/Hora", en: "Date/Time", zh: "日期/时间" },
    "col.operacion": { es: "No. Operación", en: "Operation No.", zh: "操作编号" },
    "col.caja": { es: "Caja", en: "Dry Van", zh: "干货车" },
    "col.sublinea": { es: "Sub-Línea", en: "Sub-Line", zh: "子线路" },
    "col.placascaja": { es: "Placas", en: "Plates", zh: "车牌" },
    "col.lineatransporte": { es: "Línea Transporte", en: "Transport Line", zh: "运输线路" },
    "col.arribo": { es: "Arribo", en: "Arrival", zh: "到达" },
    "col.comentariosArribo": { es: "Comentarios Arribo", en: "Arrival Comments", zh: "到达备注" },
    "col.driverid": { es: "Driver ID", en: "Driver ID", zh: "司机ID" },
    "col.driver": { es: "Nombre / Transportista", en: "Name / Carrier", zh: "姓名 / 承运人" },
    "col.placastracto": { es: "Placas Tracto", en: "Truck License", zh: "牵引车牌" },
    "col.modelo": { es: "Modelo", en: "Model", zh: "型号" },
    "col.sello": { es: "Sello Liberación", en: "Release Seal", zh: "放行封条" },
    "col.cargado": { es: "CARGADO", en: "LOADED", zh: "已装载" },
    "col.sellado_time": { es: "FECHA/HORA SELLADO", en: "SEALED DATE/TIME", zh: "封签日期/时间" },
    "col.observaciones": { es: "OBSERVACIONES", en: "OBSERVATIONS", zh: "备注" },
    "col.creado": { es: "CREADO", en: "CREATED", zh: "创建时间" },
    "col.liberacion": { es: "LIBERACIÓN", en: "RELEASE", zh: "放行" },
    "col.layout": { es: "LAYOUT", en: "LAYOUT", zh: "布局" },
    "col.ccp": { es: "CCP", en: "CCP", zh: "CCP" },
    "col.anexo29": { es: "ANEXO 29", en: "ANNEX 29", zh: "附件29" },
    "col.sello_asignado": { es: "SELLO ASIGNADO", en: "ASSIGNED SEAL", zh: "指定封条" },
    "col.dock": { es: "DOCK", en: "DOCK", zh: "月台" },
    "col.tipo": { es: "TIPO", en: "TYPE", zh: "类型" },
    "col.vehiculos": { es: "VEHÍCULOS", en: "VEHICLES", zh: "车辆数" },

    // Filtros del indicador POR CERRAR / CERRADO
    "filter.todos": { es: "Todos", en: "All", zh: "全部" },
    "filter.por_cerrar": { es: "POR CERRAR", en: "PENDING", zh: "待关闭" },
    "filter.cerrado": { es: "CERRADO", en: "CLOSED", zh: "已关闭" },
    "filter.cancelado": { es: "CANCELADO", en: "CANCELLED", zh: "已取消" },
    "filter.sin_layout": { es: "sin layout", en: "no layout", zh: "无布局" },
    "filter.sin_ccp": { es: "sin CCP", en: "no CCP", zh: "无CCP" },
    "filter.veh": { es: "veh.", en: "veh.", zh: "辆" },


    // Formulario (Modales)
    "form.caja_sec": { es: "Equipo (Caja Seca de 53')", en: "Equipment (53-foot Dry Van)" },
    "form.tracto_sec": { es: "Tracto Camión", en: "Truck Tractor" },

    // Catálogos
    "cajas.num": { es: "Número Caja", en: "Dry Van No." },
    "cajas.carrier": { es: "Carrier Enlace", en: "Linked Carrier" },
    "cajas.linea": { es: "Línea Transporte", en: "Transport Line" },
    "cajas.sublinea": { es: "Sub-Línea", en: "Sub-Line" },
    "cajas.clave": { es: "Clave Ap. 10", en: "App. 10 Code" },
    "cajas.tipo": { es: "Tipo Caja", en: "Type" },
    "cajas.placas": { es: "Placas", en: "License Plates" },
    "driver.name": { es: "Nombre (Driver ID)", en: "Name (Driver ID)" },
    "driver.carrier": { es: "Carrier Padre", en: "Parent Carrier" },
    "driver.linea": { es: "Línea de Transporte", en: "Transport Line" },
    "driver.licencia": { es: "Licencia", en: "License" },
    "driver.tel": { es: "Teléfono", en: "Phone" },
    "driver.placas": { es: "Placas Tracto", en: "Tractor Plates" },
    "tl.id": { es: "Línea ID (Key)", en: "Line ID (Key)" },
    "tl.carrier": { es: "Carrier Padre", en: "Parent Carrier" },
    "tl.comercial": { es: "Nombre Comercial", en: "Commercial Name" },
    "tl.sublinea": { es: "Nombre Sub-Línea", en: "Sub-Line Name" },
    "tl.razon": { es: "Razón Social", en: "Legal Name" },
    "tl.mexicana": { es: "Línea Mexicana", en: "Mexican Line" },
    "car.cod": { es: "Código", en: "Code" },
    "car.nombre": { es: "Nombre / Alias", en: "Name / Alias" },
    "car.razon": { es: "Razón Social", en: "Legal Name" },
    "btn.acciones": { es: "Acciones", en: "Actions", zh: "操作" },

    // Pre-Alerts
    "pre.status": { es: "Estatus", en: "Status" },
    "pre.file": { es: "Archivo", en: "File" },
    "pre.booking": { es: "Reserva / AWB", en: "Booking / AWB" },
    "pre.containers": { es: "Contenedores (Enc/Esp)", en: "Containers (Found/Expected)" },
    "pre.message": { es: "Mensaje", en: "Message" },
    "pre.mode": { es: "Modalidad", en: "Mode" },
    "pre.model": { es: "Modelo", en: "Model" },
    "pre.etd": { es: "ETD", en: "ETD" },
    "pre.dep_city": { es: "Ciudad Origen", en: "Departure City" },
    "pre.eta": { es: "ETA", en: "ETA" },
    "pre.arr_city": { es: "Ciudad Destino", en: "Arrival City" },
    "pre.invoice": { es: "Factura No", en: "Invoice No" },
    "pre.action": { es: "Acción", en: "Action" },

    // Customs Clearance
    "cust.action": { es: "Acción", en: "Action" },
    "cust.bl": { es: "Número de BL / AWB", en: "BL / AWB Number" },
    "cust.container": { es: "Número de Contenedor", en: "Container Number" },
    "cust.ata": { es: "Ata Port", en: "ATA Port" },
    "cust.pedimento": { es: "Número de Pedimento", en: "Entry / Pedimento number" },
    "cust.key": { es: "Clave", en: "Key" },
    "cust.assigned": { es: "Asignación de revisión", en: "Proforma Revision by:" },
    "cust.target": { es: "Fecha meta de finalización", en: "Target review completion date" },
    "cust.sent": { es: "1er envío de Proforma", en: "Pedimento Proforma Sent" },
    "cust.auth": { es: "Aprobación de Pedimento", en: "Pedimento Authorized" },
    "cust.pece_req": { es: "Fecha solicitud PECE", en: "PECE Request date" },
    "cust.pece_auth": { es: "Fecha autorización PECE", en: "PECE Auth date" },
    "cust.pay": { es: "Fecha de pago Ped.", en: "Pedimento Payment Date" },
    "cust.appoint": { es: "Cita de Despacho", en: "Truck appointment Date" },
    "cust.ata_fac": { es: "ATA Planta", en: "ATA factory" },
    "cust.eir": { es: "Fecha retorno vacío", en: "EIR date" },

    // Equipment Tracking
    "eq.action": { es: "Acción", en: "Action" },
    "eq.proj": { es: "Proyecto / Sección", en: "Project Section" },
    "eq.batch": { es: "Lote de Envío", en: "Shipment Batch" },
    "eq.pic": { es: "Responsable", en: "Person in charge" },
    "eq.loc": { es: "Lugar de descarga", en: "Unloading location" },
    "eq.party": { es: "Responsable descarga", en: "Unloading party" },
    "eq.tools": { es: "Herramientas descarga", en: "Unloading tools" },
    "eq.status": { es: "Estatus", en: "Status" },
    "eq.size": { es: "Tamaño/Tipo de Equipo", en: "Equipment Container Size" },
    "eq.qty": { es: "Cantidad", en: "Container Qty" },
    "eq.container": { es: "Número de Contenedor", en: "Container No." },
    "eq.bl": { es: "Número de BL", en: "BL No." },
    "eq.etd": { es: "ETD (Salida Estimada)", en: "ETD" },
    "eq.atd": { es: "ATD (Salida Real)", en: "ATD" },
    "eq.eta": { es: "ETA (Llegada a Puerto)", en: "ETA Port" },

    // Vessel / Shipment Plan Tracking
    "vt.action": { es: "Acción", en: "Action" },
    "vt.ref": { es: "Número de Ref.", en: "Ref No." },
    "vt.model": { es: "Modelo/Proyecto", en: "Model code / Items Name" },
    "vt.qty": { es: "Cantidad", en: "Qty" },
    "vt.type": { es: "Tipo Proy.", en: "Project types" },
    "vt.contract": { es: "Contrato CF", en: "CF contract No." },
    "vt.invoice": { es: "Factura CF", en: "CF Invoice No." },
    "vt.shipping": { es: "Naviera", en: "Shipping Company" },
    "vt.terminal": { es: "Terminal", en: "Terminal" },
    "vt.bl": { es: "Número de BL", en: "BL No." },
    "vt.container": { es: "Num. Contenedor", en: "Container No." },
    "vt.size": { es: "Tamaño", en: "Container Size" },
    "vt.etd": { es: "ETD Estimado", en: "ETD" },
    "vt.eta": { es: "ETA Puerto", en: "ETA Port" },
    "vt.prealert": { es: "Fecha Pre-Alerta", en: "Pre-Alert Date" },
    "vt.atd": { es: "ATD Real", en: "ATD" },
    "vt.ata": { es: "ATA Puerto", en: "ATA Port" },

    // BOM Analyzer
    "bom.estilo": { es: "ESTILO (Product No.)", en: "STYLE (Product No.)" },
    "bom.modelo": { es: "MODELO", en: "MODEL" },
    "bom.hnos_sin_bom": { es: "Hermanos sin BOM", en: "Siblings without BOM" },
    "bom.prod_sin_bom": { es: "Products sin BOM (por año)", en: "Products without BOM (by year)" },
    "bom.qty": { es: "Cantidad", en: "Qty" },
    "bom.insumo": { es: "INSUMO", en: "INPUT (ITEM)" },
    "bom.cant": { es: "CANTIDAD", en: "QUANTITY" },
    "bom.nota": { es: "NOTA", en: "NOTE" },
    "bom.regimen": { es: "RÉGIMEN", en: "REGIME" },
    "bom.desc": { es: "DESCRIPCIÓN", en: "DESCRIPTION" },
    "bom.cant_detec": { es: "CANTIDADES DETECTADAS", en: "DETECTED QUANTITIES" },
    "bom.estado": { es: "ESTADO", en: "STATUS" },
    "bom.merma": { es: "MERMA", en: "WASTE" },
    "bom.unidad": { es: "UNIDAD", en: "UNIT" },
    "bom.fechaini": { es: "FECHA.INI", en: "START.DATE" },
    "bom.fechafin": { es: "FECHA.FIN", en: "END.DATE" },

    // CI Extractor
    "ci.actions": { es: "Acciones", en: "Actions" },
    "ci.item": { es: "Ítem", en: "Item" },
    "ci.r8diff": { es: "R8 Dif", en: "R8Diff" },
    "ci.estimated": { es: "Estimado", en: "Estimated" },
    "ci.sensible": { es: "Sensible", en: "Sensible" },
    "ci.ndb": { es: "NDB", en: "NDB" },
    "ci.invoice": { es: "Factura", en: "Invoice No" },
    "ci.bl": { es: "BL / Guía", en: "BL" },
    "ci.container": { es: "Contenedor", en: "Container/Guide" },
    "ci.date": { es: "Fecha", en: "Date" },
    "ci.regimen": { es: "Régimen", en: "Regimen" },
    "ci.incoterm": { es: "Incoterm", en: "Incoterm" },
    "ci.hts": { es: "HTS", en: "HTS" },
    "ci.clavesat": { es: "Clave SAT", en: "CLAVESAT" },
    "ci.igi": { es: "IGI", en: "IGI Duty" },
    "ci.prosec": { es: "PROSEC", en: "PROSEC" },
    "ci.r8": { es: "R8", en: "R8" },
    "ci.part": { es: "Num Parte", en: "Part No" },
    "ci.model": { es: "Modelo", en: "Model" },
    "ci.english": { es: "Desc (EN)", en: "English Name" },
    "ci.desc_es": { es: "Desc (ES)", en: "Desc " },
    "ci.qty": { es: "Cant", en: "Qty" },
    "ci.um": { es: "UM", en: "UM" },
    "ci.netwt": { es: "Peso Neto", en: "Net Weight" },
    "ci.totalnetwt": { es: "Peso Neto Tot", en: "Total Net Wt" },
    "ci.unitprice": { es: "P. Unitario", en: "Unit Price" },
    "ci.total": { es: "Total", en: "Total" },

    // Dashboard
    "dash.title": { es: "Dashboard Operacional", en: "Operational Dashboard" },
    "dash.subtitle_live": { es: "DataStage — pedimentos cargados", en: "DataStage — loaded pedimentos" },
    "dash.subtitle_static": { es: "Customs Report — Sin datos cargados", en: "Customs Report — No data loaded" },
    "dash.live_badge": { es: "Datos en Vivo", en: "Live Data" },
    "dash.loading": { es: "Cargando pedimentos...", en: "Loading pedimentos..." },

    // Live KPI section
    "dash.sec_realtime": { es: "Operaciones en Tiempo Real", en: "Real-Time Operations" },
    "dash.vessels": { es: "Buques en Tránsito", en: "Vessels in Transit" },
    "dash.vessels_sub": { es: "Sin ATA Puerto", en: "No ATA Port" },
    "dash.port": { es: "En Puerto", en: "At Port" },
    "dash.port_sub": { es: "Pendiente Despacho", en: "Pending Clearance" },
    "dash.delivered": { es: "Entregados (Mes)", en: "Delivered (Month)" },
    "dash.delivered_sub": { es: "ATA Planta confirmado", en: "ATA Factory confirmed" },
    "dash.spend": { es: "Gasto Logístico", en: "Logistics Spend" },
    "dash.spend_sub": { es: "Flete+Aduana+Transporte", en: "Freight+Customs+Transport" },

    // YTD Summary section
    "dash.sec_ytd": { es: "Resumen Aduanal", en: "Customs Summary" },
    "dash.imp_ped": { es: "Pedimentos Importación", en: "Import Pedimentos" },
    "dash.exp_ped": { es: "Pedimentos Exportación", en: "Export Pedimentos" },
    "dash.imp_val": { es: "Valor Importado", en: "Import Value" },
    "dash.exp_val": { es: "Valor Exportado", en: "Export Value" },
    "dash.ytd_sub": { es: "Total YTD", en: "Total YTD" },
    "dash.usd_acc": { es: "USD acumulado", en: "USD accumulated" },
    "dash.no_data_warn": { es: "Mostrando datos en ceros. Descarga datos o sube archivos M3 en DataStage para ver información.", en: "Showing zeroed data. Download data or upload M3 files in DataStage to see information." },

    // Alert badges
    "dash.alert1": { es: "⚠ Exportaciones Julio −80%", en: "⚠ July Exports −80%" },
    "dash.alert2": { es: "⚠ Aranceles Mat. Prima Julio $188K", en: "⚠ July Raw Material Duties $188K" },
    "dash.alert3": { es: "50% revisiones concentradas en Q1", en: "50% of reviews concentrated in Q1" },
    "dash.alert4": { es: "Ahorro GID $291,600 USD YTD", en: "GID Savings $291,600 USD YTD" },

    // Import section
    "dash.sec_import": { es: "Importación", en: "Import" },
    "dash.chart_imp_vol": { es: "Volumen — Pedimentos de Importación", en: "Volume — Import Pedimentos" },
    "dash.chart_imp_vol_sub": { es: "Cantidad mensual por régimen (IN / A1 / AF)", en: "Monthly count by regime (IN / A1 / AF)" },
    "dash.chart_imp_val": { es: "Valor de Importación", en: "Import Value" },
    "dash.chart_imp_val_sub": { es: "Millones USD por mes", en: "USD Millions per month" },

    // Export section
    "dash.sec_export": { es: "Exportación", en: "Export" },
    "dash.chart_exp_vol": { es: "Volumen — Pedimentos de Exportación (RT)", en: "Volume — Export Pedimentos (RT)" },
    "dash.chart_exp_vol_sub": { es: "Cantidad mensual régimen retorno", en: "Monthly count return regime" },
    "dash.chart_exp_val": { es: "Valor de Exportación", en: "Export Value" },
    "dash.chart_exp_val_sub": { es: "Millones USD por mes", en: "USD Millions per month" },

    // Special ops + VAT
    "dash.sec_special": { es: "Operaciones Especiales y Contribuciones", en: "Special Operations & Taxes" },
    "dash.chart_special": { es: "Operaciones Especiales — Temporal a Definitivo", en: "Special Operations — Temp to Permanent" },
    "dash.chart_special_sub": { es: "Cantidad de pedimentos convertidos", en: "Converted pedimentos count" },
    "dash.chart_contrib": { es: "Contribuciones Pagadas", en: "Taxes Paid" },
    "dash.chart_contrib_sub_live": { es: "IGI + IVA por mes (DataStage)", en: "IGI + VAT per month (DataStage)" },
    "dash.chart_contrib_sub_static": { es: "(miles MXN)", en: "(thousands MXN)" },

    // Savings + Revisions
    "dash.sec_savings": { es: "Ahorros GID y Revisiones", en: "GID Savings & Revisions" },
    "dash.chart_gid": { es: "Ahorros GID Acumulados YTD", en: "GID Accumulated Savings YTD" },
    "dash.chart_gid_sub": { es: "Miles USD (clasificación arancelaria)", en: "USD Thousands (tariff classification)" },
    "dash.chart_rev": { es: "Revisiones Aduanales Import / Export", en: "Import / Export Customs Reviews" },
    "dash.chart_rev_sub": { es: "Carga archivos para ver datos", en: "Load files to see data" },
    "dash.rev_import": { es: "Revisiones Import", en: "Import Reviews" },
    "dash.rev_export": { es: "Revisiones Export", en: "Export Reviews" },

    // Specialists
    "dash.sec_specialists": { es: "Desempeño de Especialistas", en: "Specialists Performance" },

    // ── Saldo Fianza Module ──────────────────────────────────────────────────
    "sf.desktop_only":      { es: "Solo Versión de Escritorio",       en: "Desktop Version Only" },
    "sf.desktop_msg":       { es: "El módulo de Saldo Fianza requiere una resolución de pantalla más amplia. Por favor, accede desde una computadora para utilizar estas herramientas.", en: "The Saldo Fianza module requires a wider screen resolution. Please access it from a desktop computer." },

    // Metadata cards
    "sf.forma_pago":        { es: "FORMA DE PAGO",         en: "PAYMENT METHOD" },
    "sf.inst_emisora":      { es: "INSTITUCIÓN EMISORA",   en: "ISSUING INSTITUTION" },
    "sf.fianza":            { es: "FIANZA",                en: "BOND" },
    "sf.fecha_auth":        { es: "FECHA AUTORIZACIÓN",    en: "AUTHORIZATION DATE" },
    "sf.importe_doc":       { es: "IMPORTE DEL DOCUMENTO", en: "DOCUMENT AMOUNT" },
    "sf.imp_pagados":       { es: "IMPUESTOS PAGADOS",     en: "TAXES PAID" },
    "sf.imp_provisionados": { es: "IMPUESTOS PROVISIONADOS", en: "PROVISIONED TAXES" },
    "sf.imp_por_pagar":     { es: "IMPUESTOS POR PAGAR",  en: "TAXES PENDING PAYMENT" },
    "sf.saldo_utilizado":   { es: "SALDO UTILIZADO",       en: "BALANCE USED" },
    "sf.saldo_actual":      { es: "Saldo Actual de Fianza", en: "Current Bond Balance" },
    "sf.saldo_desc":        { es: "Se actualiza en tiempo real con el dato de la columna saldo final del último pedimento procesado.", en: "Updated in real time with the final balance column of the last processed pedimento." },

    // Header / toolbar
    "sf.title":             { es: "Control de Saldo Fianza",                             en: "Bond Balance Control" },
    "sf.subtitle":          { es: "Gestión contable y estado de pedimentos provisionados.", en: "Accounting management and provisioned pedimentos status." },
    "sf.mass_query":        { es: "Mass Query",        en: "Mass Query" },
    "sf.active_filters":    { es: "Filtros Activos",   en: "Active Filters" },
    "sf.plantilla":         { es: "Plantilla",         en: "Template" },
    "sf.cargar_datos":      { es: "Cargar Datos",      en: "Load Data" },
    "sf.exportar":          { es: "Exportar",          en: "Export" },
    "sf.nuevo":             { es: "Nuevo",             en: "New" },
    "sf.pago":              { es: "Pago",              en: "Payment" },
    "sf.start_date":        { es: "Fecha Inicio",      en: "Start Date" },
    "sf.end_date":          { es: "Fecha Fin",         en: "End Date" },
    "sf.borrar":            { es: "Borrar",            en: "Delete" },

    // Table
    "sf.historico":         { es: "Historial de Movimientos", en: "Movement History" },
    "sf.mostrando":         { es: "Mostrando",   en: "Showing" },
    "sf.de":                { es: "de",          en: "of" },
    "sf.col_acciones":      { es: "Acciones",          en: "Actions" },
    "sf.col_pedimento":     { es: "Pedimento",         en: "Pedimento" },
    "sf.col_nombre":        { es: "Nombre",            en: "Name" },
    "sf.col_provisionado":  { es: "Provisionado",      en: "Provisioned" },
    "sf.col_fecha_reg":     { es: "Fecha de Registro", en: "Registration Date" },
    "sf.col_pagado":        { es: "Pagado",            en: "Paid" },
    "sf.col_fecha_pago":    { es: "Fecha de Pago",     en: "Payment Date" },
    "sf.col_saldo_ini":     { es: "Saldo Inicial",     en: "Initial Balance" },
    "sf.col_saldo_fin":     { es: "Saldo Final",       en: "Final Balance" },
    "sf.no_records":        { es: "No se encontraron registros que coincidan con la búsqueda.", en: "No records found matching your search." },

    // Mass Query builder
    "sf.query_title":       { es: "Advanced Query Builder", en: "Advanced Query Builder" },
    "sf.query_desc":        { es: "Configura múltiples condiciones para filtrar los pedimentos de Fianza.", en: "Configure multiple conditions to filter Bond pedimentos." },
    "sf.q_column":          { es: "Columna",    en: "Column" },
    "sf.q_operator":        { es: "Operador",   en: "Operator" },
    "sf.q_datatype":        { es: "Tipo Dato",  en: "Data Type" },
    "sf.q_string":          { es: "String (Texto/Fecha)", en: "String (Text/Date)" },
    "sf.q_number":          { es: "Número (Montos)",      en: "Number (Amounts)" },
    "sf.q_target":          { es: "Valor Objetivo",       en: "Target Value" },
    "sf.q_values_per_line": { es: "Valores (uno por línea)", en: "Values (One per line)" },
    "sf.q_not_required":    { es: "Valor (no requerido)",    en: "Value (Not required)" },
    "sf.add_condition":     { es: "Agregar Condición", en: "Add Condition" },
    "sf.clear_all":         { es: "Limpiar Todo",      en: "Clear All" },
    "sf.run_query":         { es: "Ejecutar Búsqueda", en: "Run Query" },

    // Payment modal
    "sf.pay_title":         { es: "Registrar Pago",         en: "Register Payment" },
    "sf.pay_desc":          { es: "Selecciona un pedimento sin pagar para asentar su pago. Selecciona la fecha de liquidación.", en: "Select an unpaid pedimento to record its payment. Select the settlement date." },
    "sf.pay_pedimentos":    { es: "Pedimento(s) Sin Pagar", en: "Unpaid Pedimento(s)" },
    "sf.pay_hint":          { es: "Usa Cmd o Ctrl para selección múltiple.", en: "Use Cmd or Ctrl for multiple selection." },
    "sf.pay_fecha":         { es: "Fecha de Pago",  en: "Payment Date" },
    "sf.pay_monto":         { es: "Monto Pagado",   en: "Amount Paid" },
    "sf.pay_monto_sum":     { es: "Suma Total",      en: "Total Sum" },
    "sf.cancelar":          { es: "Cancelar",        en: "Cancel" },
    "sf.confirmar_pago":    { es: "Confirmar Pago",  en: "Confirm Payment" },

    // New record modal
    "sf.new_record_title":  { es: "Nuevo Registro de Pedimento", en: "New Pedimento Record" },
    "sf.nombre_placeholder":{ es: "Ej. Luis",   en: "e.g. Luis" },
    "sf.no_users":          { es: "No hay usuarios disponibles", en: "No users available" },
    "sf.saldo_previsto":    { es: "Saldo Inicial Previsto:",     en: "Expected Initial Balance:" },
    "sf.saldo_resultante":  { es: "Saldo Final Resultante:",     en: "Resulting Final Balance:" },
    "sf.registrar_guardar": { es: "Registrar y Guardar",         en: "Register & Save" },

    // Edit modal
    "sf.edit_title":        { es: "Editar Registro",   en: "Edit Record" },
    "sf.nombre_resp":       { es: "Nombre Responsable", en: "Responsible Name" },
    "sf.fecha_reg_short":   { es: "Fecha Reg.",         en: "Reg. Date" },
    "sf.fecha_pago_short":  { es: "Fecha Pago",         en: "Payment Date" },
    "sf.guardar_edit":      { es: "Guardar Editado",    en: "Save Edited" },

    // Shared labels repeated in forms
    "sf.pedimento_label":   { es: "Pedimento",    en: "Pedimento" },
    "sf.provisionado":      { es: "Provisionado", en: "Provisioned" },
    "sf.pagado":            { es: "Pagado",       en: "Paid" },
    "sf.fecha_registro":    { es: "Fecha de Registro", en: "Registration Date" },

    // ── Dashboard — tarjetas KPI ─────────────────────────────────────────────
    "dash.cloud_mode":      { es: "Firebase Cloud", en: "Firebase Cloud" },
    "dash.local_mode":      { es: "Local",           en: "Local" },
    "dash.all_history":     { es: "Todo el historial", en: "Full history" },
    "dash.sync_indicator":  { es: "Sincronizando datos...", en: "Syncing data..." },
    "dash.sync_msg":        { es: "Los datos no se han cargado. Sincroniza desde la nube.", en: "Data not loaded. Sync from the cloud." },
    "dash.sync_btn":        { es: "Descargar Datos", en: "Download Data" },
    "dash.syncing":         { es: "Sincronizando...", en: "Syncing..." },
    "dash.pedimentos_loaded":{ es: "pedimentos cargados", en: "pedimentos loaded" },

    // Contenedores por mes
    "dash.chart_cont_mes":       { es: "CONTENEDORES POR MES", en: "CONTAINERS BY MONTH" },
    "dash.chart_cont_mes_empty": { es: "Sin datos — sube ZIPs en DataStage", en: "No data — upload ZIPs in DataStage" },
    "dash.meses":                { es: "meses", en: "months" },
    "dash.antiguo_izq":          { es: "más antiguo a la izquierda", en: "oldest to the left" },

    // Tarjetas contenedores / facturas
    "dash.cont_imp":      { es: "TRANSACCIONES IMPORTACIÓN", en: "IMPORT TRANSACTIONS" },
    "dash.cont_imp_sub":  { es: "504 — transacciones IMP",   en: "504 — IMP transactions" },
    "dash.cont_exp":      { es: "TRANSACCIONES EXPORTACIÓN", en: "EXPORT TRANSACTIONS" },
    "dash.cont_exp_sub":  { es: "504 — transacciones EXP",   en: "504 — EXP transactions" },
    "dash.unit_cont":     { es: "trans.", en: "trans." },
    "dash.fact_imp":      { es: "FACTURAS IMPORTACIÓN",     en: "IMPORT INVOICES" },
    "dash.fact_imp_sub":  { es: "505 — facturas comerciales", en: "505 — commercial invoices" },
    "dash.fact_exp":      { es: "FACTURAS EXPORTACIÓN",     en: "EXPORT INVOICES" },
    "dash.fact_exp_sub":  { es: "505 + 507-ED (CFDIs)",     en: "505 + 507-ED (CFDIs)" },
    "dash.unit_fact":     { es: "fact.", en: "inv." },

    // Nombres de series en las gráficas
    "dash.bar_in":         { es: "Import Normal (IN)",    en: "Normal Import (IN)" },
    "dash.bar_a1":         { es: "Temporal (A1)",         en: "Temporary (A1)" },
    "dash.bar_af":         { es: "Activo Fijo (AF)",      en: "Fixed Asset (AF)" },
    "dash.bar_rt":         { es: "Exportación RT",        en: "RT Export" },
    "dash.bar_mat_prima":  { es: "Mat. Prima + Indir.",   en: "Raw Mat. + Indirect" },
    "dash.bar_activo_fijo":{ es: "Activo Fijo",           en: "Fixed Asset" },
    "dash.bar_valor_exp":  { es: "Valor (M USD)",         en: "Value (M USD)" },
    "dash.bar_igi_imp":    { es: "IGI Imp (Efectivo)",    en: "IGI Import (Cash)" },
    "dash.bar_iva_imp_ef": { es: "IVA Imp (Efectivo)",   en: "VAT Import (Cash)" },
    "dash.bar_iva_imp_fz": { es: "IVA Imp (Fianza)",     en: "VAT Import (Bond)" },
    "dash.bar_dta_imp":    { es: "DTA Imp (Efectivo)",   en: "DTA Import (Cash)" },
    "dash.bar_igi_exp":    { es: "IGI Exp",               en: "IGI Export" },
    "dash.bar_iva_exp":    { es: "IVA Exp",               en: "VAT Export" },
    "dash.bar_dta_exp":    { es: "DTA Exp",               en: "DTA Export" },
    "dash.ahorro_label":   { es: "Ahorro",                en: "Savings" },
    "dash.valor_label":    { es: "Valor",                 en: "Value" },

    // Subtítulos de gráficas con datos live
    "dash.m_mxn": { es: "M MXN", en: "M MXN" },

    // Etiquetas Imp/Exp en gráficas
    "dash.imp": { es: "Imp.", en: "Imp." },
    "dash.exp": { es: "Exp.", en: "Exp." },

    // TransportLines Modals & Alerts
    "msg.confirm_delete_tl": { es: "¿Seguro que deseas eliminar el proveedor de transporte?", en: "Are you sure you want to delete the transport provider?" },
    "msg.empty_file": { es: "El archivo está vacío o no tiene datos válidos.", en: "The file is empty or contains no valid data." },
    "msg.invalid_structure": { es: "Estructura inválida. Asegúrate de usar la plantilla descargable.", en: "Invalid structure. Make sure to use the downloadable template." },
    "msg.import_done": { es: "Importación finalizada.", en: "Import finished." },
    "msg.records_registered": { es: "líneas registradas.", en: "lines registered." },
    "tl.form.id": { es: "Ej. APL-001", en: "e.g. APL-001" },
    "tl.form.carrier": { es: "Selecciona el Carrier matriz...", en: "Select the parent Carrier..." },
    "tl.form.comercial": { es: "Ej. APL Logistics", en: "e.g. APL Logistics" },
    "tl.form.sublinea": { es: "Ej. DIVISION REEFER", en: "e.g. REEFER DIVISION" },
    "tl.form.razon": { es: "Ej. Logistics SA de CV", en: "e.g. Logistics SA de CV" },
    "tl.form.mexicana": { es: "Ej. Transportes Mexicanos SA", en: "e.g. Transportes Mexicanos SA" },
    "btn.cancelar": { es: "Cancelar", en: "Cancel" },
    "btn.guardar": { es: "Guardar", en: "Save" },
    // Cajas Modals & Alerts
    "msg.confirm_delete_caja": { es: "¿Seguro que deseas eliminar esta Caja/Contenedor?", en: "Are you sure you want to delete this Van/Container?", zh: "您确定要删除此干箱/集装箱吗？" },
    "msg.invalid_structure_cajas": { es: "Estructura inválida. Asegúrate de usar la plantilla descargable con NÚMERO CAJA y CARRIER (SCAC).", en: "Invalid structure. Make sure to use the downloadable template with DRY VAN NO and CARRIER (SCAC).", zh: "结构无效。请务必使用包含干箱号和承运商（SCAC）的可下载模板。" },
    "msg.no_valid_records": { es: "No se encontraron registros válidos. Obligatorios: NÚMERO CAJA, CARRIER (SCAC).", en: "No valid records found. Required: DRY VAN NO, CARRIER (SCAC).", zh: "未找到有效记录。必填项：干箱号、承运商 (SCAC)。" },
    "msg.confirm_process_cajas": { es: "¿Proceder?", en: "Proceed?", zh: "继续吗？" },
    "msg.process_success": { es: "¡Carga exitosa! Se procesaron", en: "Upload successful! Processed", zh: "上传成功！已处理" },
    "msg.records": { es: "registros.", en: "records.", zh: "条记录。" },
    "cajas.form.search": { es: "Buscar Caja...", en: "Search Van...", zh: "搜索干箱..." },
    "cajas.form.id": { es: "Ej. YM-4512", en: "e.g. YM-4512", zh: "例 YM-4512" },
    "cajas.form.scac": { es: "Selecciona el SCAC (Carrier)...", en: "Select SCAC (Carrier)...", zh: "选择SCAC (承运商)..." },
    "cajas.form.tl": { es: "Selecciona la Transport Line...", en: "Select Transport Line...", zh: "选择运输专线..." },
    "cajas.form.sublinea": { es: "Selecciona la Sub-Línea...", en: "Select Sub-Line...", zh: "选择支线..." },
    "cajas.form.tipo": { es: "Selecciona código y llena el tipo...", en: "Select code and fill in type...", zh: "选择代码并填写类型..." },
    "cajas.form.tipo_caja": { es: "Ej. CONTENEDOR ESTÁNDAR 40'", en: "e.g. STANDARD CONTAINER 40'", zh: "例 标准集装箱40尺" },
    "cajas.form.placas": { es: "Ej. 12-AB-3C", en: "e.g. 12-AB-3C", zh: "例 12-AB-3C" },

    // Drivers Modals & Alerts
    "msg.confirm_duplicate_driver": { es: "Ya existe un chófer registrado con el nombre {name}. ¿Estás seguro de que deseas guardar este registro duplicado?", en: "There is already a driver registered with the name {name}. Are you sure you want to save this duplicate record?", zh: "已存在名为 {name} 的司机记录。您确定要保存此重复记录吗？" },
    "msg.confirm_delete_driver": { es: "¿Seguro que deseas eliminar a este chófer?", en: "Are you sure you want to delete this driver?", zh: "您确定要删除此司机吗？" },
    "msg.drivers_registered": { es: "choferes registrados.", en: "drivers registered.", zh: "名司机已注册。" },
    "driver.form.carrier": { es: "Seleccionar Carrier...", en: "Select Carrier...", zh: "选择承运商..." },
    "driver.form.name": { es: "Ej. Juan Pérez", en: "e.g. Juan Perez", zh: "例 Juan Perez" },
    "driver.form.license": { es: "No. de Licencia", en: "License No.", zh: "驾驶证号" },
    "driver.form.license_type": { es: "Ej. FEDERAL, ESTATAL", en: "e.g. FEDERAL, STATE", zh: "例 联邦、州立" },
    "driver.form.phone": { es: "Tel o Celular", en: "Phone or Mobile", zh: "电话或手机" },
    "driver.form.tractor_plates": { es: "ABC-123", en: "ABC-123", zh: "ABC-123" },

    // Carriers Modals & Alerts
    "msg.confirm_delete_carrier": { es: "¿Seguro que deseas eliminar este carrier?", en: "Are you sure you want to delete this carrier?", zh: "您确定要删除此承运商吗？" },
    "msg.carriers_registered": { es: "carriers registrados.", en: "carriers registered.", zh: "承运商已注册。" },
    "car.form.cod": { es: "Ej. EGLV", en: "e.g. EGLV", zh: "例 EGLV" },
    "car.form.nombre": { es: "Ej. Evergreen", en: "e.g. Evergreen", zh: "例 Evergreen" },
    "car.form.razon": { es: "Ej. Evergreen Marine Corp...", en: "e.g. Evergreen Marine Corp...", zh: "例 Evergreen Marine Corp..." },

    // Asignaciones Diarias & Reservas
    "msg.error_uploading": { es: "Error subiendo archivo: {error}", en: "Error uploading file: {error}", zh: "上传文件错误: {error}" },
    "msg.fields_required": { es: "Los campos CARRIER PADRE (SCAC), LÍNEA DE TRANSPORTE, EQUIPMENT y TRUCK TRACTOR son obligatorios.", en: "The fields CARRIER (SCAC), TRANSPORT LINE, EQUIPMENT and TRUCK TRACTOR are required.", zh: "承运商（SCAC）、运输线路、设备和牵引车字段必填。" },
    "msg.slot_not_approved": { es: "El horario '{hora}' no es un slot aprobado. Por favor selecciona un horario de la lista.", en: "The time '{hora}' is not an approved slot. Please select a time from the list.", zh: "时间 '{hora}' 不是批准的时间段。请从列表中选择时间。" },
    "msg.window_started": { es: "La ventana de las {hora} ya inició. Selecciona el siguiente horario disponible.", en: "The {hora} window has already started. Select the next available time.", zh: "{hora} 窗口已开始。请选择下一个可用时间。" },
    "msg.no_slot_assigned": { es: "Horario no asignado seleccionar otra hora de ventana", en: "Time not assigned, select another window time", zh: "时间未分配，选择其他窗口时间" },
    "msg.duplicate_box": { es: "ERROR: La caja '{caja}' ya tiene una asignación registrada para el día {fecha}. No se permiten duplicados en la misma fecha operativa.", en: "ERROR: Box '{caja}' already has an assignment for {fecha}. No duplicates allowed on the same operational date.", zh: "错误：干箱 '{caja}' 已有 {fecha} 的分配。同一操作日期不允许重复。" },
    "msg.save_error": { es: "Error al guardar. Intenta de nuevo.", en: "Error saving. Try again.", zh: "保存时出错。请重试。" },
    "msg.delete_error": { es: "Error al eliminar: {error}", en: "Error deleting: {error}", zh: "删除时出错: {error}" },
    "msg.cancel_reason_required": { es: "Por favor escribe el motivo de cancelación antes de continuar.", en: "Please write the cancellation reason before continuing.", zh: "请在继续之前写下取消原因。" },
    "msg.cancel_error": { es: "Error al cancelar: {error}", en: "Error cancelling: {error}", zh: "取消时出错: {error}" },
    "msg.confirm_delete_cancel": { es: "¿Seguro que deseas eliminar/cancelar las {count} asignaciones seleccionadas?", en: "Are you sure you want to delete/cancel the {count} selected assignments?", zh: "您确定要删除/取消所选的 {count} 个分配吗？" },
    "msg.delete_some_error": { es: "Hubo un error borrando algunas asignaciones.", en: "There was an error deleting some assignments.", zh: "删除某些分配时出错。" },
    "msg.no_eligible_close": { es: "No hay operaciones elegibles para cierre manual en el rango actual.", en: "There are no eligible operations for manual closing in the current range.", zh: "当前范围内没有符合手动关闭条件的操作。" },
    "msg.confirm_manual_close": { es: "¿Cerrar manualmente {count} operación(es) pendiente(s)?\n\n• Fecha de cierre: hoy\n• Hora: 1 hora después del CCP (o tiempo actual si no hay CCP)\n• Observaciones: 'Cierre manual por caída de API'\n\nEsta acción no se puede deshacer.", en: "Manually close {count} pending operation(s)?\n\n• Closing date: today\n• Time: 1 hour after CCP (or current time if no CCP)\n• Remarks: 'Manual close due to API failure'\n\nThis action cannot be undone.", zh: "手动关闭 {count} 个未决操作吗？\n\n• 关闭日期：今天\n• 时间：CCP 之后1小时（如果没有 CCP，则为当前时间）\n• 备注：'由于 API 故障而手动关闭'\n\n此操作无法撤销。" },
    "msg.invalid_structure_asignaciones": { es: "Estructura inválida. La cabecera debe contener al menos FECHA, NÚMERO CAJA y DRIVER ID.", en: "Invalid structure. Header must contain at least DATE, DRY VAN NO and DRIVER ID.", zh: "结构无效。标题必须至少包含日期，干箱号和司机ID。" },
    "msg.import_done_relations": { es: "Importación finalizada. {imported} registros integrados relacionando maestras.", en: "Import finished. {imported} integrated records relating masters.", zh: "导入已完成。{imported} 条关联主数据的综合记录。" },
    "asig.form.cancel_reason": { es: "Escribe el motivo de cancelación...", en: "Write the cancellation reason...", zh: "填写取消原因..." },
    "asig.form.auto": { es: "Auto", en: "Auto", zh: "自动" },
    "asig.form.cfm_ref": { es: "CFM REF", en: "CFM REF", zh: "CFM参考号" },
    "asig.form.id": { es: "ID", en: "ID", zh: "ID" },
    "btn.yes": { es: "Sí", en: "Yes", zh: "是" },
    "btn.no": { es: "No", en: "No", zh: "否" },
    "asig.form.sel_carrier": { es: "Seleccionar Carrier...", en: "Select Carrier...", zh: "选择承运商..." },
    "asig.form.sel_subline": { es: "Seleccionar Sub-Line SCAC...", en: "Select Sub-Line SCAC...", zh: "选择支线 SCAC..." },
    "asig.form.optional_50": { es: "Opcional... (máx. 50 caracteres)", en: "Optional... (max 50 chars)", zh: "选填...（最多50个字符）" },
    "asig.form.cfm_example": { es: "Ej. CFM-26CFTTN-...", en: "e.g. CFM-26CFTTN-...", zh: "例 CFM-26CFTTN-..." },
    "asig.form.name": { es: "Nombre", en: "Name", zh: "名称" },
    "asig.form.plate_example": { es: "Ej. ABC-123", en: "e.g. ABC-123", zh: "例 ABC-123" },
    "asig.form.sel_models": { es: "Seleccionar modelos de producto...", en: "Select product models...", zh: "选择产品型号..." },

    // Reserva Ventanas 53
    "msg.confirm_reserva_asig": { es: "¿Confirmar esta reserva y generar/vincular registros en Asignación Diaria?", en: "Confirm this reservation and generate/link records in Daily Assignment?", zh: "确认此预订并在每日分配中生成/链接记录吗？" },
    "msg.reserva_ok": { es: "✅ Reserva confirmada.\n{partes}\n\nVe al módulo 'Asignación Diaria de Cajas Secas 53' para verificar.", en: "✅ Reservation confirmed.\n{partes}\n\nGo to the 'Daily Assignment 53 Dry Vans' module to verify.", zh: "✅ 预订已确认。\n{partes}\n\n前往“每日53尺干箱分配”模块进行验证。" },
    "msg.confirm_cancel_reserva": { es: "¿Cancelar esta reserva? Se liberará la capacidad en la ventana.", en: "Cancel this reservation? Capacity will be freed in the window.", zh: "取消此预订吗？窗口中的容量将被释放。" },
    "msg.confirm_delete_reserva": { es: "¿Eliminar definitivamente esta reserva cancelada? Esta acción no se puede deshacer.", en: "Permanently delete this cancelled reservation? This action cannot be undone.", zh: "永久删除此取消的预订吗？此操作无法撤销。" },
    "msg.confirm_delete_multiple_reservas": { es: "¿Eliminar las {count} reservas canceladas seleccionadas?", en: "Delete the {count} selected cancelled reservations?", zh: "删除选定的 {count} 个取消预订吗？" },
    "reserva.a": { es: "a", en: "to", zh: "至" },
    "reserva.demand_status_req": { es: "Las demandas deben estar en estatus Confirmada o Enviada a carriers para poder reservar.", en: "Demands must be in Confirmed or Sent to carriers status to reserve.", zh: "需求必须处于已确认或已发送给承运商的状态才能预订。" },
    "reserva.reservadas": { es: "Reservadas", en: "Reserved", zh: "已预订" },
    "reserva.pendientes": { es: "Pendientes", en: "Pending", zh: "待处理" },
    "reserva.productos": { es: "Productos", en: "Products", zh: "产品" },
    "reserva.reservas": { es: "Reservas", en: "Reservations", zh: "预订" },
    "reserva.col.horario": { es: "Horario", en: "Time", zh: "时间" },
    "reserva.col.carrier": { es: "Carrier", en: "Carrier", zh: "承运商" },
    "reserva.col.cajas": { es: "Cajas", en: "Vans", zh: "干箱" },
    "reserva.col.estatus": { es: "Estatus", en: "Status", zh: "状态" },
    "reserva.form.carrier": { es: "Carrier", en: "Carrier", zh: "承运商" },
    "reserva.form.placas": { es: "Placas", en: "Plates", zh: "车牌号" },
    "reserva.form.placas_auto": { es: "Auto desde caja", en: "Auto from van", zh: "自动从干箱" },
    "reserva.form.operador": { es: "Operador", en: "Operator", zh: "操作员" },
    "reserva.form.comentarios": { es: "Comentarios", en: "Comments", zh: "评论" },
};

// ─── Simplified Chinese translations (merged at load) ─────────────────────
const ZH: Record<string, string> = {
    "menu.cajas": "53尺干箱目录",
    "menu.asignaciones": "每日53尺干箱分配",
    "menu.drivers": "司机名录",
    "menu.líneas": "卡车运输专线",
    "menu.carriers": "承运商目录",
    "menu.dashboard": "数据看板",
    "menu.plan": "发货计划",
    "menu.prealerts": "到货预报",
    "menu.tracking": "物流跟踪",
    "menu.equipment": "设备",
    "menu.customs": "清关",
    "menu.ciextractor": "商业发票提取器",
    "menu.ai": "AI助手",
    "form.caja_sec": "设备 (53尺干箱)",
    "form.tracto_sec": "牵引车",
    "cajas.num": "干箱号",
    "cajas.carrier": "关联承运商",
    "cajas.linea": "运输线路",
    "cajas.sublinea": "支线",
    "cajas.clave": "附录10代码",
    "cajas.tipo": "类型",
    "cajas.placas": "车牌号",
    "driver.name": "姓名 (司机ID)",
    "driver.carrier": "所属承运商",
    "driver.linea": "运输线路",
    "driver.licencia": "驾驶证",
    "driver.tel": "电话",
    "driver.placas": "牵引车车牌号",
    "tl.id": "线路ID (键值)",
    "tl.carrier": "所属承运商",
    "tl.comercial": "商业名称",
    "tl.sublinea": "支线名称",
    "tl.razon": "法定名称",
    "tl.mexicana": "墨西哥线路",
    "car.cod": "代码",
    "car.nombre": "名称 / 别名",
    "car.razon": "法定名称",
    "pre.status": "状态",
    "pre.file": "文件",
    "pre.booking": "订舱号 / 航空运单",
    "pre.containers": "集装箱 (已找到/预期)",
    "pre.message": "消息",
    "pre.mode": "运输方式",
    "pre.model": "型号",
    "pre.etd": "预计离港时间",
    "pre.dep_city": "出发城市",
    "pre.eta": "预计到港时间",
    "pre.arr_city": "到达城市",
    "pre.invoice": "发票号",
    "pre.action": "操作",
    "cust.action": "操作",
    "cust.bl": "提单 / 航空运单号",
    "cust.container": "集装箱号",
    "cust.ata": "实际到港时间",
    "cust.pedimento": "报关单号",
    "cust.key": "代码",
    "cust.assigned": "报关草单审核人:",
    "cust.target": "目标审核完成日期",
    "cust.sent": "已发送报关草单",
    "cust.auth": "报关单已授权",
    "cust.pece_req": "PECE申请日期",
    "cust.pece_auth": "PECE授权日期",
    "cust.pay": "报关单付款日期",
    "cust.appoint": "卡车预约日期",
    "cust.ata_fac": "实际到厂时间",
    "cust.eir": "设备交接单日期",
    "eq.action": "操作",
    "eq.proj": "项目部",
    "eq.batch": "发货批次",
    "eq.pic": "负责人",
    "eq.loc": "卸货地点",
    "eq.party": "卸货方",
    "eq.tools": "卸货工具",
    "eq.status": "状态",
    "eq.size": "设备集装箱尺寸",
    "eq.qty": "集装箱数量",
    "eq.container": "集装箱号",
    "eq.bl": "提单号",
    "eq.etd": "预计离港时间",
    "eq.atd": "实际离港时间",
    "eq.eta": "预计到港时间",
    "vt.action": "操作",
    "vt.ref": "参考号",
    "vt.model": "型号代码 / 品名",
    "vt.qty": "数量",
    "vt.type": "项目类型",
    "vt.contract": "CF合同号",
    "vt.invoice": "CF发票号",
    "vt.shipping": "船公司",
    "vt.terminal": "码头",
    "vt.bl": "提单号",
    "vt.container": "集装箱号",
    "vt.size": "集装箱尺寸",
    "vt.etd": "预计离港时间",
    "vt.eta": "预计到港时间",
    "vt.prealert": "预警日期",
    "vt.atd": "实际离港时间",
    "vt.ata": "实际到港时间",
    "bom.estilo": "款式 (产品编号)",
    "bom.modelo": "型号",
    "bom.hnos_sin_bom": "无BOM的关联产品",
    "bom.prod_sin_bom": "无BOM的产品 (按年份)",
    "bom.qty": "数量",
    "bom.insumo": "投入项 (物料)",
    "bom.cant": "数量",
    "bom.nota": "备注",
    "bom.regimen": "贸易方式",
    "bom.desc": "描述",
    "bom.cant_detec": "检测数量",
    "bom.estado": "状态",
    "bom.merma": "损耗",
    "bom.unidad": "单位",
    "bom.fechaini": "开始日期",
    "bom.fechafin": "结束日期",
    "ci.actions": "操作",
    "ci.item": "明细",
    "ci.r8diff": "规则8差异",
    "ci.estimated": "估算",
    "ci.sensible": "敏感货物",
    "ci.ndb": "NDB",
    "ci.invoice": "发票号",
    "ci.bl": "提单",
    "ci.container": "集装箱/运单",
    "ci.date": "日期",
    "ci.regimen": "贸易方式",
    "ci.incoterm": "国际贸易术语",
    "ci.hts": "海关编码 (HTS)",
    "ci.clavesat": "SAT代码",
    "ci.igi": "进口关税 (IGI)",
    "ci.prosec": "PROSEC",
    "ci.r8": "规则8 (R8)",
    "ci.part": "零件号",
    "ci.model": "型号",
    "ci.english": "英文名称",
    "ci.desc_es": "描述",
    "ci.qty": "数量",
    "ci.um": "计量单位",
    "ci.netwt": "净重",
    "ci.totalnetwt": "总净重",
    "ci.unitprice": "单价",
    "ci.total": "总计",
    "dash.title": "运营看板",
    "dash.subtitle_live": "DataStage — 已加载的报关单",
    "dash.subtitle_static": "海关报告 — 未加载数据",
    "dash.live_badge": "实时数据",
    "dash.loading": "正在加载报关单...",
    "dash.sec_realtime": "实时运营",
    "dash.vessels": "在途船舶",
    "dash.vessels_sub": "未实际到港",
    "dash.port": "在港",
    "dash.port_sub": "待清关",
    "dash.delivered": "已送达 (本月)",
    "dash.delivered_sub": "已确认实际到厂",
    "dash.spend": "物流费用",
    "dash.spend_sub": "运费+清关+运输",
    "dash.sec_ytd": "海关数据汇总",
    "dash.imp_ped": "进口报关单",
    "dash.exp_ped": "出口报关单",
    "dash.imp_val": "进口货值",
    "dash.exp_val": "出口货值",
    "dash.ytd_sub": "本年迄今总计",
    "dash.usd_acc": "累计美元",
    "dash.no_data_warn": "显示零数据。在DataStage中下载数据或上传M3文件以查看信息。",
    "dash.alert1": "⚠ 七月出口下降80%",
    "dash.alert2": "⚠ 七月原材料关税18.8万美元",
    "dash.alert3": "50%的审核集中在第一季度",
    "dash.alert4": "本年迄今GID节省291,600美元",
    "dash.sec_import": "进口",
    "dash.chart_imp_vol": "数量 — 进口报关单",
    "dash.chart_imp_vol_sub": "按贸易方式按月统计 (IN / A1 / AF)",
    "dash.chart_imp_val": "进口货值",
    "dash.chart_imp_val_sub": "每月(百万美元)",
    "dash.sec_export": "出口",
    "dash.chart_exp_vol": "数量 — 出口报关单 (RT)",
    "dash.chart_exp_vol_sub": "每月退货/出口统计",
    "dash.chart_exp_val": "出口货值",
    "dash.chart_exp_val_sub": "每月(百万美元)",
    "dash.sec_special": "特殊运营与税收",
    "dash.chart_special": "特殊运营 — 临时转结转",
    "dash.chart_special_sub": "转换的报关单数量",
    "dash.chart_contrib": "已缴税款",
    "dash.chart_contrib_sub_live": "每月进口关税+增值税 (DataStage)",
    "dash.chart_contrib_sub_static": "(千墨西哥比索)",
    "dash.sec_savings": "GID节省与审核",
    "dash.chart_gid": "本年迄今GID累计节省",
    "dash.chart_gid_sub": "千美元 (商品归类)",
    "dash.chart_rev": "进出口海关审核",
    "dash.chart_rev_sub": "加载文件以查看数据",
    "dash.rev_import": "进口审核",
    "dash.rev_export": "出口审核",
    "dash.sec_specialists": "专员绩效",
    "sf.desktop_only": "仅限桌面版",
    "sf.desktop_msg": "保证金余额模块需要更宽的屏幕分辨率。请从台式电脑访问。",
    "sf.forma_pago": "付款方式",
    "sf.inst_emisora": "发行机构",
    "sf.fianza": "保函",
    "sf.fecha_auth": "授权日期",
    "sf.importe_doc": "单据金额",
    "sf.imp_pagados": "已缴税款",
    "sf.imp_provisionados": "计提税款",
    "sf.imp_por_pagar": "待缴税款",
    "sf.saldo_utilizado": "已用余额",
    "sf.saldo_actual": "当前保函余额",
    "sf.saldo_desc": "随着最新处理的报关单的期末余额列实时更新。",
    "sf.title": "保函余额控制",
    "sf.subtitle": "会计管理和计提报关单状态。",
    "sf.mass_query": "批量查询",
    "sf.active_filters": "活动筛选器",
    "sf.plantilla": "模板",
    "sf.cargar_datos": "加载数据",
    "sf.exportar": "导出",
    "sf.nuevo": "新建",
    "sf.pago": "付款",
    "sf.start_date": "开始日期",
    "sf.end_date": "结束日期",
    "sf.borrar": "删除",
    "sf.historico": "变动历史",
    "sf.mostrando": "显示",
    "sf.de": "共",
    "sf.col_acciones": "操作",
    "sf.col_pedimento": "报关单",
    "sf.col_nombre": "姓名",
    "sf.col_provisionado": "已计提",
    "sf.col_fecha_reg": "登记日期",
    "sf.col_pagado": "已付款",
    "sf.col_fecha_pago": "付款日期",
    "sf.col_saldo_ini": "期初余额",
    "sf.col_saldo_fin": "期末余额",
    "sf.no_records": "未找到符合您搜索条件的记录。",
    "sf.query_title": "高级查询生成器",
    "sf.query_desc": "配置多个条件以筛选保函报关单。",
    "sf.q_column": "列",
    "sf.q_operator": "运算符",
    "sf.q_datatype": "数据类型",
    "sf.q_string": "字符串 (文本/日期)",
    "sf.q_number": "数字 (金额)",
    "sf.q_target": "目标值",
    "sf.q_values_per_line": "值 (每行一个)",
    "sf.q_not_required": "值 (非必填)",
    "sf.add_condition": "添加条件",
    "sf.clear_all": "全部清除",
    "sf.run_query": "运行查询",
    "sf.pay_title": "登记付款",
    "sf.pay_desc": "选择未付款的报关单以记录其付款。选择结算日期。",
    "sf.pay_pedimentos": "未付款报关单",
    "sf.pay_hint": "使用 Cmd 或 Ctrl 进行多选。",
    "sf.pay_fecha": "付款日期",
    "sf.pay_monto": "付款金额",
    "sf.pay_monto_sum": "总计金额",
    "sf.cancelar": "取消",
    "sf.confirmar_pago": "确认付款",
    "sf.new_record_title": "新报关单记录",
    "sf.nombre_placeholder": "例如：Luis",
    "sf.no_users": "无可用用户",
    "sf.saldo_previsto": "预期期初余额:",
    "sf.saldo_resultante": "最终期末余额:",
    "sf.registrar_guardar": "登记并保存",
    "sf.edit_title": "编辑记录",
    "sf.nombre_resp": "负责人姓名",
    "sf.fecha_reg_short": "登记日期",
    "sf.fecha_pago_short": "付款日期",
    "sf.guardar_edit": "保存编辑",
    "sf.pedimento_label": "报关单",
    "sf.provisionado": "已计提",
    "sf.pagado": "已付款",
    "sf.fecha_registro": "登记日期",
    "dash.cloud_mode": "Firebase 云",
    "dash.local_mode": "本地",
    "dash.all_history": "完整历史记录",
    "dash.sync_indicator": "正在同步数据...",
    "dash.sync_msg": "数据未加载。从云端同步。",
    "dash.sync_btn": "下载数据",
    "dash.syncing": "正在同步...",
    "dash.pedimentos_loaded": "已加载报关单",
    "dash.chart_cont_mes": "每月集装箱数",
    "dash.chart_cont_mes_empty": "无数据 — 在DataStage中上传ZIP",
    "dash.meses": "月",
    "dash.antiguo_izq": "最旧的在左侧",
    "dash.cont_imp": "进口交易",
    "dash.cont_imp_sub": "504 — 进口交易",
    "dash.cont_exp": "出口交易",
    "dash.cont_exp_sub": "504 — 出口交易",
    "dash.unit_cont": "笔",
    "dash.fact_imp": "进口发票",
    "dash.fact_imp_sub": "505 — 商业发票",
    "dash.fact_exp": "出口发票",
    "dash.fact_exp_sub": "505 + 507-ED (CFDI电子发票)",
    "dash.unit_fact": "张",
    "dash.bar_in": "一般进口 (IN)",
    "dash.bar_a1": "临时进口 (A1)",
    "dash.bar_af": "固定资产 (AF)",
    "dash.bar_rt": "RT出口",
    "dash.bar_mat_prima": "原材料 + 间接物料",
    "dash.bar_activo_fijo": "固定资产",
    "dash.bar_valor_exp": "货值 (百万美元)",
    "dash.bar_igi_imp": "进口关税 (现金)",
    "dash.bar_iva_imp_ef": "进口增值税 (现金)",
    "dash.bar_iva_imp_fz": "进口增值税 (保函)",
    "dash.bar_dta_imp": "进口海关加工费DTA (现金)",
    "dash.bar_igi_exp": "出口关税",
    "dash.bar_iva_exp": "出口增值税",
    "dash.bar_dta_exp": "出口海关加工费DTA",
    "dash.ahorro_label": "节省金额",
    "dash.valor_label": "货值",
    "dash.m_mxn": "百万墨西哥比索",
    "dash.imp": "进口",
    "dash.exp": "出口",
};

// Merge ZH into translations
Object.entries(ZH).forEach(([key, zh]) => {
    if (translations[key]) (translations[key] as any).zh = zh;
    else translations[key] = { es: zh, en: zh, zh };
});

interface LanguageContextProps {
    language: Language;
    toggleLanguage: () => void;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>(() => {
        return (localStorage.getItem('logi_lang') as Language) || 'es';
    });

    useEffect(() => {
        localStorage.setItem('logi_lang', language);
    }, [language]);

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'es' ? 'en' : prev === 'en' ? 'zh' : 'es');
    };

    const t = (key: string): string => {
        const entry = translations[key];
        if (!entry) return key;
        return (entry as any)[language] ?? entry['en'] ?? entry['es'] ?? key;
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextProps => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
